CREATE TABLE `consent_template` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(100) NOT NULL,
	`consent_type` enum('treatment','surgical','anaesthetic','radiograph','photography','dataSharing') NOT NULL,
	`body_en` text NOT NULL,
	`body_am` text NOT NULL,
	`is_active` boolean NOT NULL DEFAULT true,
	`created_by` varchar(255),
	`updated_by` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(3) on update CURRENT_TIMESTAMP(3),
	`deleted_at` datetime,
	`deleted_by` varchar(255),
	CONSTRAINT `consent_template_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `consent_template` ADD CONSTRAINT `consent_template_created_by_user_id_fk` FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `consent_template` ADD CONSTRAINT `consent_template_updated_by_user_id_fk` FOREIGN KEY (`updated_by`) REFERENCES `user`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE `consent_template` ADD CONSTRAINT `consent_template_deleted_by_user_id_fk` FOREIGN KEY (`deleted_by`) REFERENCES `user`(`id`) ON DELETE set null ON UPDATE no action;--> statement-breakpoint
-- The wording a clinic starts with: `DEFAULT_CONSENT_TEMPLATES` in `src/lib/consentForms.ts`.
INSERT INTO `consent_template` (`name`, `consent_type`, `body_en`, `body_am`) VALUES
('Dental treatment', 'treatment', 'I, {patient}, agree to dental treatment at {clinic}: {treatment}.\n\nThe treatment, what it is for, and the other choices — including having no treatment — have been explained to me by {clinician}. I understand that the plan may need to change once treatment starts, and that I will be told if it does. I have been able to ask questions, and they have been answered.\n\nI understand the cost I have been quoted, and that I may withdraw this consent at any time before treatment.', 'እኔ {patient}፣ በ{clinic} የጥርስ ሕክምና ለማድረግ ተስማምቻለሁ፦ {treatment}።\n\nሕክምናው፣ ለምን እንደሚደረግ እና ሌሎች አማራጮች — ሕክምና አለማድረግንም ጨምሮ — በ{clinician} ተብራርተውልኛል። ሕክምናው ከተጀመረ በኋላ ዕቅዱ ሊቀየር እንደሚችልና ከተቀየረ እንደሚነገረኝ ተረድቻለሁ። ጥያቄዎችን ለመጠየቅ ዕድል አግኝቻለሁ፣ መልስም ተሰጥቶኛል።\n\nየተነገረኝን ዋጋ ተረድቻለሁ፤ ሕክምናው ከመጀመሩ በፊት በማንኛውም ጊዜ ይህንን ስምምነት ማንሳት እንደምችል አውቃለሁ።'),
('Surgery or extraction', 'surgical', 'I, {patient}, agree to the following surgery or extraction at {clinic}: {treatment}.\n\n{clinician} has explained why it is needed and the other choices. I understand the risks, which include pain, swelling, bleeding, infection, a dry socket, damage to nearby teeth or fillings, and — rarely — numbness of the lip, chin or tongue that may last a long time, or an opening into the sinus from an upper tooth.\n\nI will follow the care instructions I am given, and return or call if bleeding, swelling or pain gets worse.', 'እኔ {patient}፣ በ{clinic} የሚከተለውን ቀዶ ሕክምና ወይም ጥርስ ማውጣት ለማድረግ ተስማምቻለሁ፦ {treatment}።\n\n{clinician} ለምን እንደሚያስፈልግና ሌሎች አማራጮችን አብራርተውልኛል። ሊያጋጥሙ የሚችሉ ችግሮችን ተረድቻለሁ፦ ሕመም፣ እብጠት፣ ደም መፍሰስ፣ ኢንፌክሽን፣ ደረቅ ሶኬት፣ በአጠገብ ባሉ ጥርሶች ወይም ሙሌቶች ላይ ጉዳት፣ እና — አልፎ አልፎ — ለረጅም ጊዜ ሊቆይ የሚችል የከንፈር፣ የአገጭ ወይም የምላስ መደንዘዝ፣ ወይም ከላይኛው ጥርስ ወደ ሳይነስ መከፈት።\n\nየተሰጠኝን የእንክብካቤ መመሪያ እከተላለሁ፤ ደም መፍሰስ፣ እብጠት ወይም ሕመም ከተባባሰ እመለሳለሁ ወይም እደውላለሁ።'),
('Local anaesthetic or sedation', 'anaesthetic', 'I, {patient}, agree to local anaesthetic (an injection to numb the area) or sedation for {treatment} at {clinic}.\n\nI have told {clinician} about my health, my medicines and any allergy. I understand that the numbness lasts a few hours, that I must not bite or chew on the numb side until it wears off, and that rarely an injection causes bruising, a fast heartbeat, or numbness that lasts longer.\n\nIf I am sedated, an adult will take me home and stay with me, and I will not drive or sign anything important for the rest of the day.', 'እኔ {patient}፣ በ{clinic} ለ{treatment} የማደንዘዣ መርፌ (አካባቢውን የሚያደነዝዝ) ወይም ማስታገሻ እንዲሰጠኝ ተስማምቻለሁ።\n\nስለ ጤናዬ፣ ስለምወስዳቸው መድኃኒቶችና ስላለብኝ አለርጂ ለ{clinician} ነግሬያለሁ። መደንዘዙ ለጥቂት ሰዓታት እንደሚቆይ፣ እስኪለቅ ድረስ በደነዘዘው ወገን መንከስ ወይም ማኘክ እንደሌለብኝ፣ እና አልፎ አልፎ መርፌው መሰንበር፣ የልብ ምት መፍጠን ወይም ረዘም ያለ መደንዘዝ ሊያስከትል እንደሚችል ተረድቻለሁ።\n\nማስታገሻ ከተሰጠኝ አንድ አዋቂ ሰው ወደ ቤት ወስዶኝ አብሮኝ ይቆያል፤ በቀሪው ቀን መኪና አልነዳም ወይም አስፈላጊ ሰነድ አልፈርምም።'),
('Radiographs', 'radiograph', 'I, {patient}, agree to dental radiographs (X-rays) at {clinic} as {clinician} advises.\n\nI understand that dental radiographs use a very small dose of radiation, that they show what cannot be seen by looking, and that they are kept as part of my record. I have said whether I am, or may be, pregnant.', 'እኔ {patient}፣ {clinician} በሚመክሩት መሠረት በ{clinic} የጥርስ ራጅ (ኤክስሬይ) እንዲነሳልኝ ተስማምቻለሁ።\n\nየጥርስ ራጅ በጣም አነስተኛ የጨረር መጠን እንደሚጠቀም፣ በዓይን የማይታየውን እንደሚያሳይ እና የመዝገቤ አካል ሆኖ እንደሚቀመጥ ተረድቻለሁ። ነፍሰ ጡር መሆኔን ወይም ልሆን እንደምችል ተናግሬያለሁ።'),
('Clinical photographs', 'photography', 'I, {patient}, agree that {clinic} may take photographs of my mouth and face for my record and to plan my treatment.\n\nThe photographs are kept with my record and are not shown to anyone outside my care without my further written permission. I may withdraw this consent at any time.', 'እኔ {patient}፣ {clinic} ለመዝገቤና ሕክምናዬን ለማቀድ የአፌንና የፊቴን ፎቶግራፍ እንዲያነሳ ተስማምቻለሁ።\n\nፎቶግራፎቹ ከመዝገቤ ጋር ይቀመጣሉ፤ ያለ ተጨማሪ የጽሑፍ ፈቃዴ ከሕክምናዬ ውጪ ላለ ማንም አይታዩም። ይህንን ስምምነት በማንኛውም ጊዜ ማንሳት እችላለሁ።'),
('Sharing records', 'dataSharing', 'I, {patient}, agree that {clinic} may share my dental record — notes, radiographs and treatment — with: ________________________________, for: ________________________________.\n\nNothing else is shared, and only for this purpose. I may withdraw this consent at any time, in writing.', 'እኔ {patient}፣ {clinic} የጥርስ መዝገቤን — ማስታወሻዎች፣ ራጆችና ሕክምናዎች — ለ________________________________ ለ________________________________ ዓላማ እንዲያጋራ ተስማምቻለሁ።\n\nከዚህ ውጪ ምንም አይጋራም፣ ለዚህ ዓላማ ብቻ። ይህንን ስምምነት በማንኛውም ጊዜ በጽሑፍ ማንሳት እችላለሁ።');