// closures.ts - Days the clinic is shut.
import { mysqlTable, varchar, int, tinyint, date, index } from 'drizzle-orm/mysql-core';
import { relations } from 'drizzle-orm';
import { secureFields } from './secureFields';
import { branch } from './branches';

/**
 * A day, or a run of days, on which no appointment should be booked.
 *
 * The diary already knows when a clinician is unavailable — `staff_schedule` holds working hours
 * (two rows for one weekday is a lunch break), `leave` holds time off, and `operatory.isActive`
 * retires a chair. What none of them can say is that the *clinic* is closed. Without this the
 * day view will happily offer slots on Ethiopian Christmas.
 *
 * **`branchId` is nullable with no default, and null means every branch.** This deliberately
 * breaks the `branchRef()` pattern used everywhere else, because here "belongs to no particular
 * branch" is a real and common state rather than a missing value: a public holiday closes all of
 * them, while renovation closes one. Defaulting to the main branch would silently leave the
 * others open on Meskel.
 *
 * **Gregorian dates are authoritative**; the Ethiopian pair below is metadata. The diary asks
 * "is this date inside a closure", and that has to be a plain indexed range check, not a
 * calendar conversion per row.
 *
 * Non-goal: half days. A clinic that shuts at noon on New Year's Eve is better served by the
 * per-weekday hours in `staff_schedule` than by a second, overlapping notion of partial time
 * here.
 */
export const clinicClosure = mysqlTable(
	'clinic_closure',
	{
		id: int('id').primaryKey().autoincrement(),

		/** Null means every branch. See the note above — this is not `branchRef()`. */
		branchId: int('branch_id').references(() => branch.id, { onDelete: 'cascade' }),

		/** "Meskel", "Ethiopian Christmas", "Renovation". */
		name: varchar('name', { length: 100 }).notNull(),

		/** Inclusive. A single-day closure has the same date in both. */
		startsOn: date('starts_on').notNull(),
		endsOn: date('ends_on').notNull(),

		/**
		 * The Ethiopian month and day this falls on, when it is a holiday fixed to the Ethiopian
		 * calendar — Meskerem 1 for Enkutatash, Tahsas 29 for Ethiopian Christmas. Set, it means
		 * the closure recurs every year and next year's dates can be generated from it.
		 *
		 * **Null for the movable feasts, and that is the point of storing this at all.** Fasika
		 * follows the Orthodox computus and Eid al-Fitr and Eid al-Adha follow the Islamic
		 * calendar, so neither lands on a fixed Ethiopian date and neither can be generated by
		 * rule. Those are entered by hand each year, and a null here is what marks them as needing
		 * it rather than letting them silently fail to appear.
		 */
		ethiopianMonth: tinyint('ethiopian_month'),
		ethiopianDay: tinyint('ethiopian_day'),

		note: varchar('note', { length: 255 }),

		...secureFields
	},
	(table) => [
		// "Is this day closed" — an overlap test on a range, which is why the dates are Gregorian.
		index('clinic_closure_range_idx').on(table.startsOn, table.endsOn),
		index('clinic_closure_branch_idx').on(table.branchId)
	]
);

export const clinicClosureRelations = relations(clinicClosure, ({ one }) => ({
	branch: one(branch, { fields: [clinicClosure.branchId], references: [branch.id] })
}));
